/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as MorningRouteImport } from './routes/morning'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as BuildRouteImport } from './routes/build'
import { Route as BreakRouteImport } from './routes/break'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BuildIndexRouteImport } from './routes/build.index'
import { Route as BreakIndexRouteImport } from './routes/break.index'
import { Route as BuildHabitIdRouteImport } from './routes/build.$habitId'
import { Route as BreakHabitIdRouteImport } from './routes/break.$habitId'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MorningRoute = MorningRouteImport.update({
  id: '/morning',
  path: '/morning',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildRoute = BuildRouteImport.update({
  id: '/build',
  path: '/build',
  getParentRoute: () => rootRouteImport,
} as any)
const BreakRoute = BreakRouteImport.update({
  id: '/break',
  path: '/break',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildIndexRoute = BuildIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuildRoute,
} as any)
const BreakIndexRoute = BreakIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BreakRoute,
} as any)
const BuildHabitIdRoute = BuildHabitIdRouteImport.update({
  id: '/$habitId',
  path: '/$habitId',
  getParentRoute: () => BuildRoute,
} as any)
const BreakHabitIdRoute = BreakHabitIdRouteImport.update({
  id: '/$habitId',
  path: '/$habitId',
  getParentRoute: () => BreakRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/break': typeof BreakRouteWithChildren
  '/build': typeof BuildRouteWithChildren
  '/history': typeof HistoryRoute
  '/morning': typeof MorningRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/break/$habitId': typeof BreakHabitIdRoute
  '/build/$habitId': typeof BuildHabitIdRoute
  '/break/': typeof BreakIndexRoute
  '/build/': typeof BuildIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/history': typeof HistoryRoute
  '/morning': typeof MorningRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/break/$habitId': typeof BreakHabitIdRoute
  '/build/$habitId': typeof BuildHabitIdRoute
  '/break': typeof BreakIndexRoute
  '/build': typeof BuildIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/break': typeof BreakRouteWithChildren
  '/build': typeof BuildRouteWithChildren
  '/history': typeof HistoryRoute
  '/morning': typeof MorningRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/break/$habitId': typeof BreakHabitIdRoute
  '/build/$habitId': typeof BuildHabitIdRoute
  '/break/': typeof BreakIndexRoute
  '/build/': typeof BuildIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/break'
    | '/build'
    | '/history'
    | '/morning'
    | '/settings'
    | '/setup'
    | '/break/$habitId'
    | '/build/$habitId'
    | '/break/'
    | '/build/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/history'
    | '/morning'
    | '/settings'
    | '/setup'
    | '/break/$habitId'
    | '/build/$habitId'
    | '/break'
    | '/build'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/break'
    | '/build'
    | '/history'
    | '/morning'
    | '/settings'
    | '/setup'
    | '/break/$habitId'
    | '/build/$habitId'
    | '/break/'
    | '/build/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BreakRoute: typeof BreakRouteWithChildren
  BuildRoute: typeof BuildRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  MorningRoute: typeof MorningRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/morning': {
      id: '/morning'
      path: '/morning'
      fullPath: '/morning'
      preLoaderRoute: typeof MorningRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build': {
      id: '/build'
      path: '/build'
      fullPath: '/build'
      preLoaderRoute: typeof BuildRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/break': {
      id: '/break'
      path: '/break'
      fullPath: '/break'
      preLoaderRoute: typeof BreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build/': {
      id: '/build/'
      path: '/'
      fullPath: '/build/'
      preLoaderRoute: typeof BuildIndexRouteImport
      parentRoute: typeof BuildRoute
    }
    '/break/': {
      id: '/break/'
      path: '/'
      fullPath: '/break/'
      preLoaderRoute: typeof BreakIndexRouteImport
      parentRoute: typeof BreakRoute
    }
    '/build/$habitId': {
      id: '/build/$habitId'
      path: '/$habitId'
      fullPath: '/build/$habitId'
      preLoaderRoute: typeof BuildHabitIdRouteImport
      parentRoute: typeof BuildRoute
    }
    '/break/$habitId': {
      id: '/break/$habitId'
      path: '/$habitId'
      fullPath: '/break/$habitId'
      preLoaderRoute: typeof BreakHabitIdRouteImport
      parentRoute: typeof BreakRoute
    }
  }
}

interface BreakRouteChildren {
  BreakHabitIdRoute: typeof BreakHabitIdRoute
  BreakIndexRoute: typeof BreakIndexRoute
}

const BreakRouteChildren: BreakRouteChildren = {
  BreakHabitIdRoute: BreakHabitIdRoute,
  BreakIndexRoute: BreakIndexRoute,
}

const BreakRouteWithChildren = BreakRoute._addFileChildren(BreakRouteChildren)

interface BuildRouteChildren {
  BuildHabitIdRoute: typeof BuildHabitIdRoute
  BuildIndexRoute: typeof BuildIndexRoute
}

const BuildRouteChildren: BuildRouteChildren = {
  BuildHabitIdRoute: BuildHabitIdRoute,
  BuildIndexRoute: BuildIndexRoute,
}

const BuildRouteWithChildren = BuildRoute._addFileChildren(BuildRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BreakRoute: BreakRouteWithChildren,
  BuildRoute: BuildRouteWithChildren,
  HistoryRoute: HistoryRoute,
  MorningRoute: MorningRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
